
platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'OCP2' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

target 'OCP2Tests' do
  inherit! :search_paths
  # Pods for testing
end

use_native_modules!
end

target 'OCP2-tvOS' do
# Pods for rn_djxapp-tvOS

target 'OCP2-tvOSTests' do
  inherit! :search_paths
  # Pods for testing
end

end
